export default [
    {
        "roll":1001,
        "name":"Atul",
        "gender":"male",
        "branch":"CS"
    },
    {
        "roll":1002,
        "name":"Ankita",
        "gender":"female",
        "branch":"IT"
    },
    {
        "roll":1003,
        "name":"Cheeku",
        "gender":"male",
        "branch":"CS"
    },
    {
        "roll":1006,
        "name":"Peeku",
        "gender":"male",
        "branch":"CV"
    },
    {
        "roll":1004,
        "name":"Maansi",
        "gender":"female",
        "branch":"CV"
    },
    {
        "roll":1005,
        "name":"Ritik",
        "gender":"male",
        "branch":"MECH"
    }
];